#+TITLE: Documenting the Progress of Writing Weechat Plugin in Rust

* Disclaimer

If you wanna write Weechat Plugin, there's already a great lib written by poljar, 
https://github.com/poljar/rust-weechat

Otherwise, If you wanna know how to write those *-sys crate, go to
https://kornel.ski/rust-sys-crate
instead

This is a documentation about me trying to understand the ffi primitives in rust.
It's based on rewriting perl script for weechat, highmon, in rust.
I don't use cargo since I wanna use as little magic as possible.
And the real goal is to understand what actually happened.

* Docs Links

https://weechat.org/files/doc/devel/weechat_plugin_api.en.html

* File to Include

~weechat-plugin.h~

Get it from the install path in ~$PREFIX/include/weechat/weechat-plugin.h~
Or from the source tree in ~$CHECKOUT/src/plugins/weechat-plugin.h~

* bindgen

#+BEGIN_SRC sh-session
$ bindgen weechat-plugin.h -o plugin.rs
#+END_SRC

Wait a few minutes for it to finish.


* C Examples

See ~example.c~. Also inspect the ~Makefile~ on how to compile and where to install the resulting plugin.

* C Macro in weechat-plugin.h

How to translate it?

Ans: Expand it manually

* How to Export char[]?

#+BEGIN_SRC rust
#[no_mangle]
pub static foo: [u8; $SIZE] = *b"$CONTENT\0";
#+END_SRC

* RIIR Target

https://github.com/KenjiE20/highmon/blob/dfc885e4a68191ec4fec0c0f51775bbdbaa0494a/highmon.pl

(this should point to current master as of this writing)

* Nomicon Docs

https://doc.rust-lang.org/nomicon/ffi.html

* Helper C2Rust

https://c2rust.com/


* A Working Reference/Attempt

https://github.com/poljar/rust-weechat

* How to Represent #define String Literal?

For example

#+BEGIN_EXAMPLE
#define WEECHAT_CONFIG_OPTION_NULL "null"
#+END_EXAMPLE

* Resource About Rust FFI

https://kornel.ski/rust-sys-crate


* plugin.rs done, but without string constant

* Start RIIR-ing

** Creating New Buffer
